packages:
  - "apps/*"
  - "packages/*"
  - "packages/config/*"
allowBuilds:
  '@nestjs/core': set this to true or false
  '@prisma/engines': true
  '@scarf/scarf': set this to true or false
  bcrypt: set this to true or false
  esbuild: true
  prisma: true
  sharp: set this to true or false
  unrs-resolver: true
